spring:
  application:
    name: Journal App
  data:
    mongodb:
      uri: mongodb+srv://rayanmitra2021:ryan2003@cluster0.w8tvl.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true