spring:
  application:
    name: Journal App
  data:
    redis:
      host: redis-17726.c305.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 17726
      password: Tbm425rkURgNtqBKphVp0LHPuKtV7jeR
#      uri: redis://default:Tbm425rkURgNtqBKphVp0LHPuKtV7jeR@redis-17726.c305.ap-south-1-1.ec2.redns.redis-cloud.com:17726

    mongodb:
      uri: mongodb+srv://rayanmitra2021:ryan2003@cluster0.w8tvl.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rayan.mitra2021@vitstudent.ac.in
    password: pqrh zlub wdjm rptz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080


weather:
  api:
    key: 9a15360aa6b78f6748e5d2ae3cc0a4cc